apiVersion: apps/v1
kind: Deployment
metadata:
  name: examensarbete-app
  namespace: examensarbete-app
  labels:
    app: examensarbete
    team: um
    owner: maddun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examensarbete
  template:
    metadata:
      labels:
        app: examensarbete
        team: um
        owner: maddun
    spec:
      containers:
        - name: examensarbete
          image: acrexamensarbete.azurecr.io/secuflow:v3
          securityContext:
            privileged: true
