apiVersion: apps/v1
kind: Deployment
metadata:
  name: privileged-app
  namespace: examensarbete-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
        - name: nginx
          image: nginx
          securityContext:
            privileged: true
