apiVersion: v1
kind: Pod
metadata:
  name: if-not-present
  namespace: examensarbete-app
  labels:
    team: um
    owner: maddun
spec:
  containers:
    - name: app
      image: nginx:1.25
      imagePullPolicy: IfNotPresent
